<a href="https://colab.research.google.com/github/Nagul21/Numpy_task/blob/main/Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [10]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [9]:
import numpy as np
Zero=np.zeros(10)
print(Zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [8]:
import numpy as np
arr = np.zeros((100,100))
print(arr.size)
print(arr.itemsize)
print(arr.size * arr.itemsize)

10000
8
80000


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [13]:
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [11]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [12]:
print(np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [16]:
arr = np.arange(1,11)
arr = arr[::-1]
print(arr)

[10  9  8  7  6  5  4  3  2  1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [19]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [21]:
numbers=[1,2,0,0,4,0]
print(np.nonzero(numbers))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [22]:
print(np.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [23]:
print(np.random.random((3,3,3)))


[[[0.37138598 0.02686783 0.85045902]
  [0.36337347 0.97618339 0.22306466]
  [0.07409148 0.6478985  0.22337581]]

 [[0.7477228  0.72787729 0.06401713]
  [0.1348897  0.13683737 0.63643338]
  [0.05057092 0.73094935 0.82323621]]

 [[0.72163719 0.32622022 0.40305914]
  [0.91683346 0.93771316 0.27617216]
  [0.4353372  0.03328473 0.22298509]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [24]:
RV=np.random.random((10,10))
print(RV)
print(RV.min())
print(RV.max())

[[0.9654321  0.36937363 0.6670629  0.12121331 0.79978011 0.69395233
  0.99345887 0.0933783  0.990091   0.32859681]
 [0.62897738 0.57162837 0.32545832 0.86613562 0.91036574 0.18803372
  0.16282538 0.67340079 0.2391751  0.46770609]
 [0.72360243 0.58835789 0.57263791 0.39572804 0.39107716 0.47927079
  0.06310839 0.7845288  0.51814037 0.29766796]
 [0.81868773 0.00423348 0.17406929 0.17591776 0.93496671 0.68241628
  0.99613425 0.77366953 0.08350402 0.68123537]
 [0.0589746  0.79780242 0.90632168 0.51365313 0.81033204 0.657895
  0.43675472 0.81507345 0.0821149  0.09355237]
 [0.6625052  0.0463236  0.48902549 0.18861325 0.24965558 0.89063159
  0.918373   0.38570161 0.03186603 0.80933038]
 [0.13515717 0.23344682 0.04832918 0.76165855 0.77178976 0.74926088
  0.65973435 0.90944011 0.36294714 0.47310923]
 [0.29909839 0.06700927 0.39268142 0.99262694 0.20320697 0.3344585
  0.42074866 0.53932845 0.52468832 0.10567461]
 [0.86567954 0.79743489 0.83900433 0.29214368 0.07678547 0.76881006
  0.6052743  0.

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [25]:
R_vec= np.random.random(30)
print(R_vec)
print(R_vec.mean())

[0.89842406 0.0430068  0.22126542 0.31807944 0.62638661 0.19440497
 0.62300647 0.20024555 0.33823608 0.18887302 0.54780125 0.82032391
 0.34051975 0.60390308 0.4904358  0.52008968 0.80341474 0.84125307
 0.38133064 0.32927578 0.81485091 0.48712768 0.4403022  0.84225932
 0.67548416 0.23984821 0.77193286 0.17378657 0.85619669 0.79007411]
0.5140712939923395


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [26]:
two_d= np.ones((10,10))
two_d[1:-1,1:-1] = 0
print(two_d)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [27]:
one=np.ones((3,3))
pad=np.pad(one,1)
print(pad)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [28]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [29]:
diagonal= np.diag(1+np.arange(4), k = -1)
print (diagonal)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [32]:
CB = np.zeros((8,8),dtype=int)
CB[1::2,::2] = 1
CB[::2,1::2] = 1
print(CB)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [33]:
print(np.unravel_index(100,(6,7,8)))


(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [35]:
CB = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(CB)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [36]:
arr = np.random.random((5,5))
Normal = (arr - arr.min())/(arr.max() - arr.min())
print(Normal)

[[0.39940816 0.00693245 0.94745056 0.21637078 0.4706084 ]
 [0.54790619 1.         0.71834122 0.03871318 0.55325481]
 [0.64756849 0.         0.22727125 0.84025788 0.80468052]
 [0.34281759 0.13833098 0.17659205 0.78205345 0.59629511]
 [0.47197903 0.55685656 0.11286603 0.16401025 0.82660231]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [37]:
one = np.random.random((5,3))
two = np.random.random((3,2))
result=np.dot(one,two)
print(result)

[[0.2701011  0.21318308]
 [0.94795345 1.10609024]
 [0.52822104 0.23349878]
 [1.15829781 0.67980517]
 [0.70084268 0.59478534]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [38]:
negation = np.arange(11)
negation[(3 < negation) & (negation <= 7)] *= -1
print(negation)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [39]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [25]:
Z=np.array([1,4,9],dtype=int)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)


[        1       256 387420489]
[  1   8 256]
[False False False]
[0.+1.j 0.+4.j 0.+9.j]
[1. 4. 9.]


ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [41]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))
print("\n")

nan
0
[-9.22337204e+18]




/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [42]:
round = np.random.uniform(-10, +10, 10)
np.copysign(np.ceil(np.abs(round)),round)

array([-5., -6.,  5., -4.,  2.,  3., -8.,  4.,  1., -7.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [44]:
comman1 =np.array([0, 1, 2, 3, 4])
comman2 =np.array([9, 6, 2, 5, 0])
print(np.intersect1d(comman1, comman2))

[0 2]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [3]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [4]:
today = np.datetime64('today', 'D')
print("Today's date is : ", today)
yesterday = np.datetime64('today', 'D')- np.timedelta64(1, 'D') 
print("Yesterday's date is : ", yesterday)
tomorrow = np.datetime64('today', 'D')+ np.timedelta64(1, 'D')  
print("Tomorrow's date is : ", tomorrow)

Today's date is :  2022-10-30
Yesterday's date is :  2022-10-29
Tomorrow's date is :  2022-10-31


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [5]:
July = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(July)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [6]:
one = np.ones(2)*1
two = np.ones(2)*2
np.add(one,two,out=two)
np.divide(one,2,out=one)
np.negative(one,out=one)
np.multiply(one,two,out=one)

array([-1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [7]:
Extract = np.random.uniform(0,10,10)

print (Extract - Extract%1)
print (np.floor(Extract))
print (np.ceil(Extract)-1)
print (Extract.astype(int))
print (np.trunc(Extract))

[3. 4. 8. 0. 3. 4. 0. 4. 9. 3.]
[3. 4. 8. 0. 3. 4. 0. 4. 9. 3.]
[3. 4. 8. 0. 3. 4. 0. 4. 9. 3.]
[3 4 8 0 3 4 0 4 9 3]
[3. 4. 8. 0. 3. 4. 0. 4. 9. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [9]:
mat = np.zeros((5,5),dtype=int)
mat = mat + np.arange(5)
print(mat)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [10]:
linespace=np.linspace(0,1,10)
print(linespace)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [11]:
sorting =np.random.random(10)
sorting.sort()
print(sorting)

[0.04956142 0.08192023 0.10633814 0.16342087 0.4310416  0.48438518
 0.54450284 0.59590043 0.73250799 0.94684112]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [13]:
addition=np.arange(15)
print(np.add.reduce(addition))

105


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [14]:
A =np.array([1,2,3,4,5,6])
B= np.array([1,2,3,4,5,6])
print(np.allclose(A,B))
C =np.array([1,2,3,4,9,6])
D= np.array([1,10,3,4,5,6])
print(np.array_equal(C,D))


True
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [16]:
RV= np.random.random(10)
RV[RV.argmax()] = 0
print(RV)

[0.58594234 0.60363381 0.43193315 0.69406318 0.52969068 0.61385266
 0.82773164 0.30890559 0.26227941 0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [19]:
x_value = np.random.random((2,2))
y_value = np.random.random((2,2))
result = 1 / (x_value-y_value)
result = 1 / np.subtract.outer(x_value,y_value)
np.linalg.det(result)

array([[ 49.78053731,  12.61046161],
       [ 51.35988332, 158.61785105]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [20]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [22]:
np.set_printoptions(threshold=float("inf"))
arr= np.ones((5,5),dtype=int)
print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [23]:
value1= np.arange(100)
value2 = np.random.uniform(0,100)
index = (np.abs(value1-value2)).argmin()
print(value1[index])

83


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [24]:
Convert= np.arange(10, dtype=np.int32)
Convert = Convert.astype(np.float32, copy=False)
print(Convert)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [25]:
listed = np.arange(9).reshape(3,3)
for i, j in np.ndenumerate(listed):
    print(i,j)
for i in np.ndindex(listed.shape):
    print(i, listed[i])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [26]:
value = 5
point= 3
arr = np.zeros((value,value))
np.put(arr, np.random.choice(range(value*value),point,replace=False),1)
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [27]:
value= np.random.rand(5,10)
result = value-value.mean(axis=1,keepdims=True)
print(result)

[[-0.28844075 -0.07206889  0.16718439  0.18972314  0.49194651 -0.36406783
  -0.38290202 -0.3133506   0.05345862  0.51851743]
 [ 0.02867501  0.02819351 -0.11219483 -0.38226018  0.08334699  0.00052246
  -0.04415299  0.32819243  0.17916482 -0.10948722]
 [-0.31022205  0.15035701  0.20008884  0.21071134 -0.18799107 -0.27806078
  -0.37570787  0.21780977  0.32447754  0.04853727]
 [ 0.33351658  0.41807433 -0.03517371  0.18088425 -0.14897457 -0.30163507
  -0.44027977 -0.34351305  0.13428368  0.20281732]
 [-0.26300357  0.24682146  0.20345927 -0.28977102 -0.42873123 -0.16582656
   0.17133439  0.43130706  0.23882096 -0.14441076]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [28]:
sort_col= np.random.randint(1,25,(3,3))
print(sort_col)
print(sort_col[sort_col[:,1].argsort()])

[[21 21 22]
 [ 3 10 22]
 [15  5  4]]
[[15  5  4]
 [ 3 10 22]
 [21 21 22]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [29]:
two_D= np.random.randint(1,3,(2,10))
print((~two_D.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [30]:
Value1 = np.random.uniform(0,1,10)
Value2 = 0.5
result = Value1.flat[np.abs(Value1 - Value2).argmin()]
print(result)

0.3245486750669778


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [31]:
value1 = np.ones(10)
integer= np.random.randint(0,len(value1),20)
value1 += np.bincount(integer,minlength=len(value1))
print(value1)

np.add.at(value1,integer, 1)
print(value1)

[3. 3. 4. 2. 1. 4. 3. 5. 2. 3.]
[5. 5. 7. 3. 1. 7. 5. 9. 3. 5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [33]:
x_value= np.random.randint(1,10,6)
y_value = np.random.randint(1,10,6)
result = np.bincount(x_value,y_value)
print(result)

[0. 0. 8. 9. 0. 0. 4. 5.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [3]:
Value = np.random.randint(1,11,(3,4,3,4))
sum = Value.sum(axis=(-2,-1))
print(sum)
sum = Value.reshape(Value.shape[:-2]+(-1,)).sum(axis=-1)
print(sum)

[[50 77 45 72]
 [55 65 67 61]
 [50 56 63 54]]
[[50 77 45 72]
 [55 65 67 61]
 [50 56 63 54]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [7]:
Value1 = np.random.uniform(0,1,100)
Value2 = np.random.randint(0,10,100)
value1_re = np.bincount(Value2,weights=Value1)
value1_counts = np.bincount(Value2)
Value1_means = value1_re / value1_counts
print(Value1_means)
import pandas as pd
print(pd.Series(Value1).groupby(Value2).mean())

[0.305735   0.48851882 0.53990222 0.39059646 0.50233605 0.41525951
 0.59303133 0.53310368 0.52879831 0.48752663]
0    0.305735
1    0.488519
2    0.539902
3    0.390596
4    0.502336
5    0.415260
6    0.593031
7    0.533104
8    0.528798
9    0.487527
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [9]:
diag1 = np.random.uniform(1,5,(5,5))
diag2 = np.random.uniform(1,5,(5,5))
print(np.diag(np.dot(diag1,diag2)))

[58.60562276 32.52022518 37.25778343 35.47409156 53.97475037]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [10]:
arr= np.array([11,22,33,44,55])
no_of_ze = 3
arr_val = np.zeros(len(arr) + (len(arr)-1)*(no_of_ze))
arr_val[::no_of_ze+1] = arr
print(arr_val)

[11.  0.  0.  0. 22.  0.  0.  0. 33.  0.  0.  0. 44.  0.  0.  0. 55.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [12]:
arr1= np.ones((5,5,3))
arr2= 5*np.ones((5,5))
print(arr1*arr2[:,:,None])

[[[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [13]:
arr = np.arange(25).reshape(5,5)
arr[[2,3]] = arr[[3,2]]
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]
 [10 11 12 13 14]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [15]:
arr1= np.bincount([0,1,2,3,4,5,6])
arr2= np.repeat(np.arange(len(arr1)),arr1)
print(arr2)

[0 1 2 3 4 5 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [16]:
arr = np.random.randint(0,2,100)
print(np.logical_not(arr,out=arr))


[1 0 0 0 1 1 0 1 1 0 1 1 1 0 1 1 0 1 0 0 0 1 1 0 0 1 0 1 1 0 1 0 0 1 1 0 1
 1 0 1 0 1 1 1 0 1 0 1 1 1 1 0 1 1 1 1 0 0 0 1 0 0 1 0 1 1 1 1 0 1 1 0 0 0
 0 0 0 1 1 1 1 0 0 1 1 0 1 0 0 1 1 1 1 0 0 0 1 1 1 0]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [18]:
arr = np.random.uniform(0,1,(10,10))
A,B,C = np.linalg.svd(arr)
rank = np.sum(B > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [19]:
freq = np.random.randint(1,11,10)
print(np.bincount(freq).argmax())

5


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [20]:
A,B = 1,2
X = np.ones((A,B,B))
Y = np.ones((A,B,1))
Z = np.tensordot(X,Y,axes=[[0, 2], [0, 1]])
print(Z)

[[2.]
 [2.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [21]:
ran = np.arange(100)
np.random.shuffle(ran)
val = 5
print (ran[np.argpartition(-ran,val)[:val]])

[97 98 99 96 95]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [22]:
x = np.random.rand(int(5e7))
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.73 s ± 14.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
145 ms ± 914 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
123 ms ± 614 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [23]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 3 4 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)